-- MySQL Script generated by MySQL Workbench
-- Sun Jan 28 19:11:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_WinGoods
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_WinGoods` ;

-- -----------------------------------------------------
-- Schema DB_WinGoods
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_WinGoods` DEFAULT CHARACTER SET utf8 ;
USE `DB_WinGoods` ;

-- -----------------------------------------------------
-- Table `DB_WinGoods`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `idusers_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `category_color` INT NOT NULL,
  `category_icon` INT NOT NULL,
  `sync_status` INT NOT NULL DEFAULT '0',
  `user_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `user_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC),
  INDEX `fk_categories_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DB_WinGoods`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`goods` (
  `good_id` INT NOT NULL AUTO_INCREMENT,
  `good_name` VARCHAR(45) NOT NULL,
  `quantity_level` INT NOT NULL DEFAULT '1',
  `is_to_buy` INT NOT NULL DEFAULT '1',
  `sync_status` INT NOT NULL DEFAULT '0',
  `category_id` INT NOT NULL,
  PRIMARY KEY (`good_id`, `category_id`),
  UNIQUE INDEX `good_id_UNIQUE` (`good_id` ASC),
  INDEX `fk_goods_categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_goods_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `DB_WinGoods`.`categories` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`co_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`co_users` (
  `co_user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `user_id` INT NULL,
  `confirmation_status` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`co_user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_co_users_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_co_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `DB_WinGoods`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DB_WinGoods`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_WinGoods`;
INSERT INTO `DB_WinGoods`.`users` (`user_id`, `email`, `password`, `user_name`) VALUES (1, 'omar.haji@gmail.com', 'aaaaaa', 'omar.haji');

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_WinGoods`.`categories`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_WinGoods`;
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (1, 'FRUITS & LEGUMES', 2131099679, 2131230875, 1, 1);
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (3, 'VIANDES & POISSONS', 2131099709, 2131230872, 1, 1);
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (2, 'PAIN & VIENNOISERIES', 2131099686, 2131230816, 1, 1);
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (4, 'MARCHAND D\'EPICES', 2131099708, 2131230871, 1, 1);
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (6, 'ALIMENTATION GENERALE', 2131099732, 2131230830, 1, 1);
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (5, 'MENAGE & HYGIENE', 2131099733, 2131230826, 1, 1);
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (7, 'FROMAGES & CHARCUTERIE', 2131099773, 2131230818, 1, 1);
INSERT INTO `DB_WinGoods`.`categories` (`category_id`, `category_name`, `category_color`, `category_icon`, `sync_status`, `user_id`) VALUES (8, 'DIVERS', 2131099707, 2131230864, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_WinGoods`.`goods`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_WinGoods`;
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (1, 'Carottes', 1, 1, 1, 1);
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (3, 'Viande hachée', 1, 1, 1, 3);
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (2, 'Pain', 1, 1, 1, 2);
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (4, 'Cumin', 1, 1, 1, 4);
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (6, 'Sauce tomate', 1, 1, 1, 6);
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (5, 'Dentifrice', 1, 1, 1, 5);
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (7, 'Kiri', 1, 1, 1, 7);
INSERT INTO `DB_WinGoods`.`goods` (`good_id`, `good_name`, `quantity_level`, `is_to_buy`, `sync_status`, `category_id`) VALUES (8, 'Lampe', 1, 1, 1, 8);

COMMIT;

