-- MySQL Script generated by MySQL Workbench
-- Sat Jul 14 14:04:44 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP TABLE goods;
DROP TABLE categories;
DROP TABLE co_users;
DROP TABLE users;


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_WinGoods
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_WinGoods` ;

-- -----------------------------------------------------
-- Schema DB_WinGoods
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_WinGoods` DEFAULT CHARACTER SET utf8 ;
USE `DB_WinGoods` ;

-- -----------------------------------------------------
-- Table `DB_WinGoods`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`users` (
  `server_user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  PRIMARY KEY (`server_user_id`),
  UNIQUE INDEX `idusers_UNIQUE` (`email` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`server_user_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`categories` (
  `server_category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `category_color` INT NOT NULL,
  `category_icon` INT NOT NULL,
  `sync_status` INT NOT NULL DEFAULT '0',
  `email` VARCHAR(45) NOT NULL,
  `device_category_id` INT NOT NULL,
  `server_user_id` INT NOT NULL,
  PRIMARY KEY (`server_category_id`, `server_user_id`),
  INDEX `fk_categories_users1_idx` (`server_user_id` ASC),
  UNIQUE INDEX `category_id_UNIQUE` (`server_category_id` ASC),
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`server_user_id`)
    REFERENCES `DB_WinGoods`.`users` (`server_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`goods` (
  `server_good_id` INT NOT NULL AUTO_INCREMENT,
  `good_name` VARCHAR(45) NOT NULL,
  `quantity_level` INT NOT NULL DEFAULT '1',
  `is_to_buy` INT NOT NULL DEFAULT '1',
  `sync_status` INT NOT NULL DEFAULT '0',
  `device_good_id` INT NOT NULL,
  `device_category_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `server_category_id` INT NOT NULL,
  PRIMARY KEY (`server_good_id`, `server_category_id`),
  UNIQUE INDEX `good_id_UNIQUE` (`server_good_id` ASC),
  INDEX `fk_goods_categories_idx` (`server_category_id` ASC),
  CONSTRAINT `fk_goods_categories`
    FOREIGN KEY (`server_category_id`)
    REFERENCES `DB_WinGoods`.`categories` (`server_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`co_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`co_users` (
  `server_co_user_id` INT NOT NULL AUTO_INCREMENT,
  `device_co_user_id` INT NULL,
  `co_user_email` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `confirmation_status` INT NOT NULL,
  `has_responded` INT NOT NULL,
  `sync_status` INT NOT NULL,
  `server_user_id` INT NOT NULL,
  PRIMARY KEY (`server_co_user_id`, `server_user_id`),
  INDEX `fk_co_users_users1_idx` (`server_user_id` ASC),
  CONSTRAINT `fk_co_users_users1`
    FOREIGN KEY (`server_user_id`)
    REFERENCES `DB_WinGoods`.`users` (`server_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
