-- MySQL Script generated by MySQL Workbench
-- Mon Sep 10 13:22:41 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_WinGoods
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_WinGoods` ;

-- -----------------------------------------------------
-- Schema DB_WinGoods
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_WinGoods` DEFAULT CHARACTER SET utf8 ;
USE `DB_WinGoods` ;

-- -----------------------------------------------------
-- Table `DB_WinGoods`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`groups` (
  `server_group_id` INT NOT NULL AUTO_INCREMENT,
  `group_name` VARCHAR(45) NOT NULL,
  `owner_email` VARCHAR(45) NOT NULL,
  `server_owner_id` VARCHAR(45) NOT NULL,
  `sync_status` INT NOT NULL,
  PRIMARY KEY (`server_group_id`),
  UNIQUE INDEX `server_group_id_UNIQUE` (`server_group_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`users` (
  `server_user_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `server_group_id` INT NULL,
  `update_available` INT NOT NULL DEFAULT 0,
  `sign_up_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`server_user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`server_user_id` ASC),
  INDEX `fk_users_groups1_idx` (`server_group_id` ASC),
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`server_group_id`)
    REFERENCES `DB_WinGoods`.`groups` (`server_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`categories` (
  `server_category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  `category_color` INT NOT NULL,
  `category_icon` INT NOT NULL,
  `sync_status` INT NOT NULL DEFAULT '0',
  `email` VARCHAR(45) NOT NULL,
  `device_category_id` INT NOT NULL,
  `last_update_user_id` INT NOT NULL,
  `crud_status` INT NOT NULL DEFAULT 0,
  `server_user_id` INT NOT NULL,
  PRIMARY KEY (`server_category_id`, `server_user_id`),
  INDEX `fk_categories_users1_idx` (`server_user_id` ASC),
  UNIQUE INDEX `category_id_UNIQUE` (`server_category_id` ASC),
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`server_user_id`)
    REFERENCES `DB_WinGoods`.`users` (`server_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`goods` (
  `server_good_id` INT NOT NULL AUTO_INCREMENT,
  `good_name` VARCHAR(45) NOT NULL,
  `quantity_level` INT NOT NULL DEFAULT '1',
  `is_to_buy` INT NOT NULL DEFAULT '1',
  `sync_status` INT NOT NULL DEFAULT '0',
  `device_good_id` INT NOT NULL,
  `device_category_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `last_update_user_id` INT NOT NULL,
  `crud_status` INT NOT NULL DEFAULT 0,
  `server_category_id` INT NOT NULL,
  `good_desc` VARCHAR(45) NULL,
  `server_originator_id` INT NOT NULL,
  PRIMARY KEY (`server_good_id`, `server_category_id`),
  UNIQUE INDEX `good_id_UNIQUE` (`server_good_id` ASC),
  INDEX `fk_goods_categories_idx` (`server_category_id` ASC),
  CONSTRAINT `fk_goods_categories`
    FOREIGN KEY (`server_category_id`)
    REFERENCES `DB_WinGoods`.`categories` (`server_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`co_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`co_users` (
  `server_co_user_id` INT NOT NULL AUTO_INCREMENT,
  `device_co_user_id` INT NULL,
  `co_user_email` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `confirmation_status` INT NOT NULL,
  `has_responded` INT NOT NULL,
  `sync_status` INT NOT NULL,
  `server_user_id` INT NOT NULL,
  PRIMARY KEY (`server_co_user_id`, `server_user_id`),
  INDEX `fk_co_users_users1_idx` (`server_user_id` ASC),
  UNIQUE INDEX `server_co_user_id_UNIQUE` (`server_co_user_id` ASC),
  CONSTRAINT `fk_co_users_users1`
    FOREIGN KEY (`server_user_id`)
    REFERENCES `DB_WinGoods`.`users` (`server_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`shop_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`shop_types` (
  `server_shop_type_id` INT NOT NULL AUTO_INCREMENT,
  `shop_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`server_shop_type_id`),
  UNIQUE INDEX `server_shop_type_id_UNIQUE` (`server_shop_type_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`countries` (
  `server_country_id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`server_country_id`),
  UNIQUE INDEX `server_country_id_UNIQUE` (`server_country_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`cities` (
  `server_city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `server_country_id` INT NOT NULL,
  PRIMARY KEY (`server_city_id`, `server_country_id`),
  INDEX `fk_city_country1_idx` (`server_country_id` ASC),
  UNIQUE INDEX `server_city_id_UNIQUE` (`server_city_id` ASC),
  UNIQUE INDEX `city_name_UNIQUE` (`city_name` ASC),
  CONSTRAINT `fk_city_country1`
    FOREIGN KEY (`server_country_id`)
    REFERENCES `DB_WinGoods`.`countries` (`server_country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`shops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`shops` (
  `server_shop_id` INT NOT NULL AUTO_INCREMENT,
  `shop_name` VARCHAR(45) NULL,
  `shop_adress` VARCHAR(45) NULL,
  `store_email` VARCHAR(45) NULL,
  `shop_phone` VARCHAR(45) NULL,
  `longitude` DOUBLE NULL,
  `latitude` DOUBLE NULL,
  `server_shop_type_id` INT NOT NULL,
  `server_city_id` INT NOT NULL,
  `server_country_id` INT NOT NULL,
  PRIMARY KEY (`server_shop_id`, `server_shop_type_id`, `server_city_id`, `server_country_id`),
  INDEX `fk_stores_store_types1_idx` (`server_shop_type_id` ASC),
  INDEX `fk_shops_city1_idx` (`server_city_id` ASC, `server_country_id` ASC),
  UNIQUE INDEX `server_shop_id_UNIQUE` (`server_shop_id` ASC),
  CONSTRAINT `fk_stores_store_types1`
    FOREIGN KEY (`server_shop_type_id`)
    REFERENCES `DB_WinGoods`.`shop_types` (`server_shop_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shops_city1`
    FOREIGN KEY (`server_city_id` , `server_country_id`)
    REFERENCES `DB_WinGoods`.`cities` (`server_city_id` , `server_country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`shopkeepers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`shopkeepers` (
  `server_shopkeeper_id` INT NOT NULL AUTO_INCREMENT,
  `shopkeeper_email` VARCHAR(45) NOT NULL,
  `shopkeeper_password` VARCHAR(45) NOT NULL,
  `shopkeeper_name` VARCHAR(45) NOT NULL,
  `shopkeeper_phone` VARCHAR(45) NULL,
  `server_shop_id` INT NOT NULL,
  `server_shop_type_id` INT NOT NULL,
  PRIMARY KEY (`server_shopkeeper_id`, `server_shop_id`, `server_shop_type_id`),
  INDEX `fk_shopkeepers_shops1_idx` (`server_shop_id` ASC, `server_shop_type_id` ASC),
  UNIQUE INDEX `server_shopkeeper_id_UNIQUE` (`server_shopkeeper_id` ASC),
  CONSTRAINT `fk_shopkeepers_shops1`
    FOREIGN KEY (`server_shop_id` , `server_shop_type_id`)
    REFERENCES `DB_WinGoods`.`shops` (`server_shop_id` , `server_shop_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`orders` (
  `server_order_id` INT NOT NULL AUTO_INCREMENT,
  `server_user_id` INT NOT NULL,
  `server_shop_id` INT NOT NULL,
  `server_shop_type_id` INT NOT NULL,
  `order_status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`server_order_id`, `server_user_id`, `server_shop_id`, `server_shop_type_id`),
  INDEX `fk_orders_users1_idx` (`server_user_id` ASC),
  INDEX `fk_orders_shops1_idx` (`server_shop_id` ASC, `server_shop_type_id` ASC),
  UNIQUE INDEX `server_order_id_UNIQUE` (`server_order_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`server_user_id`)
    REFERENCES `DB_WinGoods`.`users` (`server_user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_shops1`
    FOREIGN KEY (`server_shop_id` , `server_shop_type_id`)
    REFERENCES `DB_WinGoods`.`shops` (`server_shop_id` , `server_shop_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_WinGoods`.`ordered_goods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_WinGoods`.`ordered_goods` (
  `server_ordered_good_id` INT NOT NULL,
  `server_good_id` INT NOT NULL,
  `server_category_id` INT NOT NULL,
  `server_order_id` INT NOT NULL,
  `server_user_id` INT NOT NULL,
  `server_shop_id` INT NOT NULL,
  `server_shop_type_id` INT NOT NULL,
  `good_name` VARCHAR(45) NOT NULL,
  `good_desc` VARCHAR(45) NULL,
  INDEX `fk_ordered_goods_goods1_idx` (`server_good_id` ASC, `server_category_id` ASC),
  INDEX `fk_ordered_goods_orders1_idx` (`server_order_id` ASC, `server_user_id` ASC, `server_shop_id` ASC, `server_shop_type_id` ASC),
  UNIQUE INDEX `server_ordered_good_id_UNIQUE` (`server_ordered_good_id` ASC),
  PRIMARY KEY (`server_ordered_good_id`, `server_shop_id`, `server_order_id`, `server_user_id`, `server_shop_type_id`),
  CONSTRAINT `fk_ordered_goods_goods1`
    FOREIGN KEY (`server_good_id` , `server_category_id`)
    REFERENCES `DB_WinGoods`.`goods` (`server_good_id` , `server_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordered_goods_orders1`
    FOREIGN KEY (`server_order_id` , `server_user_id` , `server_shop_id` , `server_shop_type_id`)
    REFERENCES `DB_WinGoods`.`orders` (`server_order_id` , `server_user_id` , `server_shop_id` , `server_shop_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
